[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-common.workspace = true
aoc-data.workspace = true
itertools.workspace = true
nalgebra.workspace = true
nom.workspace = true
strum.workspace = true
z3.workspace = true

[dev-dependencies]
rstest.workspace = true
