[package]
name = "aoc-2015"
version = "0.1.0"
edition = "2024"

[dependencies]
aoc-common.workspace = true
aoc-data.workspace = true
nom.workspace = true

md5 = { version = "0.8.0" }

[dev-dependencies]
rstest.workspace = true
